---

- include: "install_pyenv_{{ ansible_os_family }}.yml"

- name: add pyenv vars to zshrc
  blockinfile:
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      if [ command -v pyenv 1>/dev/null 2>&1 ] ; then
        eval "$(pyenv init -)"
        pyenv virtualenvwrapper_lazy
      fi
      export WORKON_HOME="$HOME/.virtualenvs"
      export PROJECT_HOME="$HOME/projects"
    marker: ### pyenv vars ###

- name: Install system python packages
  pip:
    name: "{{ item }}"
    state: latest
    extra-args: --user
  become: yes
  become_method: sudo
  with_items: "{{ python_packages }}"

- name: install pyenv versions
  command: pyenv install {{ item }}
  with_items: "{{ pyenv_versions }}"

- name: restart shell with pyenv
  shell: exec "$SHELL"
