---

- include: "install_pyenv_{{ ansible_os_family }}.yml"

- name: add pyenv vars to zshrc
  blockinfile:
    path: "{{ home_dir }}/.zshrc"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      eval "$(pyenv init -)"
      pyenv virtualenvwrapper_lazy
      export WORKON_HOME="$HOME/.virtualenvs"
      export PROJECT_HOME="$HOME/Projects"
    marker: "### {mark} pyenv vars ###"

- name: install pyenv versions
  shell: pyenv install {{ item }}
  with_items: "{{ pyenv_versions }}"
  ignore_errors: true

- name: source pyenv into environment
  shell: eval {{ item }}
  with_items:
    - "$(pyenv init -)"
    - "$(pyenv virtualenvwrapper_lazy)"
  ignore_errors: true

- name: set up pyenv virtualenvs
  shell: pyenv virtualenv {{ item.version }} {{ item.name }}; pyenv activate {{ item.name }}; {{ item.commands|join('; ') }}; pyenv deactivate
  with_items: "{{ virtualenvs }}"
  ignore_errors: true

- name: set pyenv globals
  shell: pyenv global {{ (pyenv_versions + virtualenvs|map(attribute='name')|list)|join(' ') }}

- name: restart shell with pyenv
  shell: exec "$SHELL"

