---

nodejs_nvm_ver: "0.33.1"
nodejs_nvm_install_url: "https://raw.githubusercontent.com/creationix/nvm/v{{nodejs_nvm_ver}}/install.sh"
nodejs_nvm_install_script: "{{home_dir}}/tmp/install.sh"
nodejs_default_ver: "8.9.4"
nodejs_versions:
  - "6.10"
nodejs_versions_to_remove:
  - "0.10.43"
  - "0.12.12"
  - "0.10.44"
  - "0.10.45"
  - "0.10.46"
  - "0.10.47"
  - "0.10.48"
  - "0.12.13"
  - "0.12.14"
  - "0.12.15"
  - "0.12.16"
  - "0.12.17"
  - "0.12.18"
  - "4.6.2"
  - "4.2.4"
  - "5.9.1"
  - "5.10.1"
  - "5.12.0"
  - "6.5.0"
nodejs_npm_packages:
  - serverless
  - create-react-app
  - eslint
  - jshint
  - jsxhint
  - webpack
  - craftool
