---

- name: Update homebrew
  command: "brew update"

- name: Install base homebrew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
  with_items: "{{ brew_base_packages }}"
  tags:
    - base
    - brew

- name: Install updated brew cask applications
  command: "brew cask install {{item.install_options | default('') }} {{ item.name }}"
  with_items: "{{ brew_cask_applications }}"
  tags:
    - base
    - brew
    - brew-cask
# TODO: Put this in when on 2.2 which is broken right now
# - name: Install brew cask applications
#   homebrew_cask:
#     name: "{{ item.name }}"
#     state: "{{ item.state | default('present') }}"
#   install_options: "{{item.install_options | default('') }}"
#   with_items: "{{ brew_cask_applications }}"

- name: Cleanup homebrew
  command: "brew cleanup -s"
  ignore_errors: True
  tags:
    - brew
    - cleanup

- name: Cleanup cask
  command: "brew cask cleanup"
  ignore_errors: True
  tags:
    - base
    - brew
    - brew-cask
    - cleanup

- name: Link homebrew apps
  command: "brew linkapps"
  tags:
    - base
    - brew
    - brew-cask

