---

- name: Update homebrew
  command: "brew update"
  tags:
    - darwin
    - brew

- name: add brew taps
  debug: msg="adding brew tap {{ item }}"
  homebrew_tap: tap={{ item }} state="{{ item.state | default('present') }}"
  with_items: "{{ brew_taps }}"
  tags:
    - darwin
    - brew

- name: Install base homebrew packages
  homebrew:
    name: "{{ item }}"
    install_options: ''
    state: latest
    with_items: "{{ brew_packages }}"
  tags:
    - darwin
    - brew

- name: Install brew cask applications
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  install_options: "{{item.install_options | default('') }}"
  with_items: "{{ cask_bins }}"
  tags:
    - darwin
    - brew

- name: Cleanup homebrew
  command: "brew cleanup -s"
  ignore_errors: True
  tags:
    - darwin
    - brew

- name: Cleanup cask
  command: "brew cask cleanup"
  ignore_errors: True
  tags:
    - darwin
    - brew

- name: Link homebrew apps
  command: "brew linkapps"
  tags:
    - darwin
    - brew

