---

- include: "install_{{ ansible_os_family }}.yml"

- name: install neovim python plugin
  pip:
    name: neovim
    state: present
    extra_args: --user

- name: Make "{{ neovim_config_dir }}/autoload" directory
  file: path="{{ neovim_config_dir }}/autoload" state=directory

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_config_dir }}/autoload/plug.vim"
    force: yes

- name: symlink vimrc file
  file:
    src: files/init.vim
    dest: ~/.vimrc
    state: link

- name: install neovim plugins
  command: nvim '+silent! PlugInstall!' +qall!

